from textwrap3 import wrap

text = 'Hello user! Thank you for agreeing to take this test. In this test, you are expected to find the discriminant of an equation generated by the program using the formula: b^2 - 4ac. Enter a number below to start...'

x = wrap(text, 39)
for i in range(len(x)):
    print(x[i])